percentile_circles endpoint added to api
HSLdevcom/hfp-analytics pull request #35
Opened 2022-08-31 14:07 UTC by Divinare

Closes #23

2022-08-31 14:43 UTC, datarttu requested changes
The core functionality looks really good, just commented some metadata nuances, Postgres function optimization, and possibly wrapping the FeatureCollection building process into a function in Python side.

2022-08-31 14:43 UTC, datarttu commented on db/sql/400_api.sql
> +'Returns jore_stops as GeoJSON features';
Suggested: `'Returns all jore_stops as GeoJSON features';`

2022-08-31 14:43 UTC, datarttu commented on db/sql/400_api.sql
> +'Returns stop_medians as GeoJSON features';
Suggested: `'Returns all stop_medians as GeoJSON features';`

2022-08-31 14:43 UTC, datarttu commented on db/sql/400_api.sql
>  $$ LANGUAGE SQL VOLATILE;
Not touched in this PR, but I think `STABLE` can be used in this function for potentially better query optimization than with stricter `VOLATILE`. `STABLE` allows for database lookups (which `IMMUTABLE` does not) that we do here, this is just a "read-only" function whose result depends on the argument values and the database state. `VOLATILE` would be needed if we modified the database with the function and/or used values from functions like `random()`.

You can try changing this within this PR or just add a TODO.

2022-08-31 14:43 UTC, datarttu commented on db/sql/400_api.sql
> +'Returns observations with null stop_id as GeoJSON features';
Suggested: `'Returns observations with no stop_id value, but located within search_distance_m from the given stop_id, as GeoJSON features';`

2022-08-31 14:43 UTC, datarttu commented on db/sql/400_api.sql
> +$$ LANGUAGE SQL VOLATILE;
Same here as above, read-only function that can be `STABLE` instead of `VOLATILE`.

2022-08-31 14:43 UTC, datarttu commented on db/sql/400_api.sql
> +'Returns percentile circles with stop_id as GeoJSON features';
Suggested: `'Returns percentile circles around given stop_id as GeoJSON features';`

2022-08-31 14:43 UTC, datarttu commented on python/api/main.py
> +    Returns a GeoJSON FeatureCollection of percentile circles with given stop_id.
Suggested: `Returns a GeoJSON FeatureCollection of percentile circles around the given stop by stop_id.`

2022-08-31 14:43 UTC, datarttu commented on python/api/main.py
> +            percentile_circle_geojson_features = []
Seems like we have a repeated pattern here, common for all these endpoints returning a FeatureCollection. At the same time, the current `get_feature_collection()` func does pretty little compared to this pattern. Maybe we could wrap the whole thing to a function in `common.utils`, e.g. like this?

```python
def tuples_to_feature_collection(geom_tuples: list[tuple]) -> dict
    """Transforms GeoJSON tuples returned by psycopg into a FeatureCollection dict for REST API."""
    # Effectively the same as the list initialization + for loop phase:
    features = [tp[0] for tp in geom_tuples]
    # Then what the current get_feature_collection() does (making that function obsolete now):
    return {
        "type": "FeatureCollection",
        "features": features
    }
```

which would be used here like

```python
return tuples_to_feature_collection(percentile_circles)
```

2022-09-01 06:44 UTC, Divinare commented
Good points, fixed everything as suggested.

2022-09-02 10:17 UTC, datarttu commented
Looks good, think this is ready for merge!

2022-09-05 10:07 UTC, merged